var scenario_one = "\
[show_bg] image/black.png\n\
[center] 这是一个发生在迎来末日的世界的故事。\n\
[center] 人类毁灭机器人的计划落败，遭到机器人的疯狂反击，几乎全灭。\n\
[center] 剩下的一些人，为了夺回人类的世界，成立了反击组织，持续和机器人军队进行着战斗。\n\
[center] 某一天，完成任务的夜、月两人正在机器人的追击下逃脱。\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/bg.png\
"

var scenario_two = "\
[stop_bgm] \n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/title.png\n\
[l_character] image/yoru.png\n\
[l_dialogue] 总算都解决了吗……真是烦人啊，这些机器人。\n\
[r_dialogue] 不要抱怨了，毕竟这也是我们的任务。\n\
[r_character] image/tsuki.png\n\
[l_dialogue] 但是老是被指派这种无聊的任务，你不觉得无聊吗？\n\
[r_dialogue] 完成任务，这就是我们现在的全部了。\n\
[l_dialogue] ……\n\
[l_dialogue] 说起来，这附近的地形还真是复杂啊……\n\
[r_dialogue] 不要掉以轻心，如果掉进陷阱里肯定就被那些机器人抓住了。\n\
[l_dialogue] 是是~\n\
[r_dialogue] 是只需要说一次就行了。\n\
[l_dialogue] 是~\n\
[r_dialogue] 真是的……都叫你不要掉以轻……\n\
[play_sound] sound/shake.wav\n\
[r_dialogue] 刚才的是！？\n\
[l_dialogue] ……我有一种不好的预感。\n\
[play_sound] sound/shake.wav\n\
[l_dialogue] 小心！\n\
[convert_bg] image/black.png\n\
[center] 哼，有意思，竟然能躲开啊。\n\
[center] 不愧是残余的人类的精英。\n\
[convert_bg] image/title.png\n\
[l_character] image/yoru.png\n\
[r_character] image/tsuki.png\n\
[r_dialogue] 那，那究竟是……\n\
[l_dialogue] 之前从来没有见过的类型！\n\
[convert_bg] image/black.png\n\
[center] 那么，接下来，你们能撑到什么时候呢？\n\
[convert_bg] image/title.png\n\
[play_sound] sound/shake.wav\n\
[play_sound] sound/shake.wav\n\
[play_sound] sound/shake.wav\n\
[l_character] image/yoru.png\n\
[r_character] image/tsuki.png\n\
[l_dialogue] 咕……\n\
[convert_bg] image/black.png\n\
[center] 到此为止了吗。\n\
[center] 你们人类也就这种程度啊。\n\
[convert_bg] image/title.png\n\
[l_character] image/yoru.png\n\
[r_character] image/tsuki.png\n\
[l_dialogue] 可恶……\n\
[r_dialogue] 咕……\n\
[l_dialogue] 月，你没事吧！？\n\
[convert_bg] image/black.png\n\
[center] 哼，到这种关头，还是顾好你自己吧！\n\
[convert_bg] image/title.png\n\
[play_sound] sound/shake.wav\n\
[l_character] image/yoru.png\n\
[l_dialogue] 啊！\n\
[r_dialogue] 夜！\n\
[l_dialogue] 这里交给我，你快走！\n\
[r_dialogue] 我怎么能够把你一个人留……\n\
[l_dialogue] 够了快给我走！\n\
[convert_bg] image/black.png\n\
[center] 哈哈哈，人类的互帮互助吗。\n\
[center] 虽然很精彩，不过差不多该结束了。\n\
[convert_bg] image/title.png\n\
[l_character] image/yoru.png\n\
[l_dialogue] 月，快闪开！\n\
[play_sound] sound/shake.wav\n\
[l_dialogue] 啊！\n\
[r_dialogue] 夜！\n\
[l_dialogue] 快……快走\n\
[r_dialogue] ……\n\
[l_dialogue] 月……你一定要好好活下去啊……\n\
[r_dialogue] ……\n\
[l_dialogue] 走啊！\n\
[r_dialogue] 啊！！！！！\n\
[convert_bg] image/black.png\n\
[center] 哦？这就是人类所谓的牺牲自己吗。\n\
[center] ……\n\
[center] 真是可笑。\n\
[center] 那我就满足你的愿望。\n\
[play_sound] sound/shake.wav\n\
[play_sound] sound/shake.wav\n\
[play_sound] sound/shake.wav\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[play_bgm] music/title.mp3\n\
[center] ……\n\
[center] 啊……一不小心又走神了。\n\
[center] 已经过去多长时间了呢？\n\
[convert_bg] image/evening.png\n\
[center] 当我回过神来的时候，夜空高悬在我的头顶。\n\
[center] 明亮的月光照在我的脸上。\n\
[center] 此刻那一轮明月看到的我，是什么模样呢？\n\
[convert_bg] image/black.png\n\
[center] 距离那一天，已经过去了多久了呢？\n\
[center] 自从那天以后，每次回过神来的时候，我都是站在这里。\n\
[center] 那一天，就在这里，夜为了救我……\n\
[center] ……\n\
[center] 我应该怎么办……\n\
[center] 没有了你，我应该怎么活下去……\n\
[convert_bg] image/title.png\n\
[r_character] image/tsuki.png\n\
[l_dialogue] 真是的，又一个人在这里吗。\n\
[r_dialogue] ……\n\
[l_dialogue] 已经过去快一个月了，差不多该振作起来了吧。\n\
[r_dialogue] ……\n\
[l_dialogue] 虽然你的心情我也可以理解……\n\
[r_dialogue] ……\n\
[l_dialogue] 但是如果看到你这个样子，夜会高兴吗？\n\
[convert_bg] image/black.png\n\
[center] 是啊。\n\
[center] 明明是夜救了我。\n\
[center] 明明是夜让我好好活下去。\n\
[center] 但是我却变成了现在的样子。\n\
[center] 夜，对不起。\n\
[center] ……但是。\n\
[center] 我唯独不想失去的就是你。\n\
[center] 如果能够再见你一面……\n\
[center] ……\n\
[center] ……\n\
[center] ……\n\
[stop_bgm]\n\
[center] “喂！你有在听我说话吗！”\n\
[convert_bg] image/title.png\n\
[r_character] image/tsuki.png\n\
[r_dialogue] 怎么了？\n\
[l_dialogue] 终于肯听我说话了吗……\n\
[r_dialogue] 没事的话请让我一个人待着。\n\
[l_dialogue] 等……等等！\n\
[l_dialogue] 哎……大小姐你为什么总是这么冷淡啊。\n\
[r_dialogue] 你想挨打吗？\n\
[l_dialogue] ……\n\
[l_dialogue] 咳咳好了，切入正题吧。\n\
[l_dialogue] 据情报说，夜好像只是被关押在了敌人的领地中。\n\
[r_dialogue] 你刚才说什么！？\n\
[l_dialogue] 就是说，夜可能还活着。\n\
[l_dialogue] 所以说……\n\
[r_dialogue] 走吧。\n\
[play_bgm] music/bg2.mp3\n\
[l_dialogue] ……哎？\n\
[r_dialogue] 快点啊！\n\
[l_dialogue] 知道了知道了……\n\
[r_dialogue] “知道了”只说一次就够了。\n\
[l_dialogue] ……知道了。\n\
[convert_bg] image/black.png\n\
[center] 夜，这次换我来救你了。\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/bg.png\
"

var scenario_three = "\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/bg.png\n\
[l_dialogue] 虽然情报这么说，但是还不知道确切的真假呢。\n\
[l_dialogue] 是机器人的陷阱也说不定。\n\
[r_character] image/tsuki.png\n\
[r_dialogue] 陷阱也没有关系，只要能救出夜。\n\
[l_dialogue] 是……\n\
[l_dialogue] 不过说回来，这附近的火力可真强啊。\n\
[r_dialogue] 难道我们的行动被发现了？\n\
[l_dialogue] 按理说不应该啊……啊，又来了一个敌人。\n\
[r_dialogue] 这种类型的敌人，没怎么见过呢。\n\
[l_dialogue] 这应该就是所谓的“叶月型”机体吧。\n\
[r_dialogue] “叶月型”？\n\
[l_dialogue] 嗯，总之，这种机体会放出强激光，小心一点吧。\n\
[r_dialogue] 激光？那不是很容易被击中吗？\n\
[l_dialogue] 虽然是这么说，但是这种机体的攻击有一个弱点。\n\
[r_dialogue] 弱点？\n\
[l_dialogue] 嗯，由于机型偏向陈旧，其激光产生伤害需要一定时间。\n\
[l_dialogue] 在这之前闪避开，应该就没问题了！\n\
[r_dialogue] 知道了！\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/bg.png\
"

var scenario_four = "\
[stop_bgm]\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/bg.png\n\
[r_character] image/tsuki.png\n\
[r_dialogue] 呼，总算是成功解决掉了啊。\n\
[l_dialogue] 嗯，接下来就是潜入了。\n\
[r_dialogue] 嗯，小心行事。\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/title.png\n\
[play_sound] sound/shake.wav\n\
[l_dialogue] 可恶，被发现了吗。\n\
[r_character] image/tsuki.png\n\
[r_dialogue] 没办法了，强行突入吧。\n\
[l_dialogue] 嗯，走吧！\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/bg.png\
"

var scenario_five = "\
[convert_bg] image/black.png\n\
[convert_bg] image/title.png\n\
[l_dialogue] 可恶，又来了一个大家伙吗！？\n\
[r_character] image/tsuki.png\n\
[r_dialogue] 夜就在前面了，解决这个家伙吧！\n\
[l_dialogue] 这个不用你说！\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/bg.png\
"

var scenario_six = "\
[stop_bgm]\n\
[convert_bg] image/title.png\n\
[l_dialogue] ……\n\
[r_character] image/tsuki.png\n\
[r_dialogue] ……\n\
[l_dialogue] ……看起来，解决掉了呢。\n\
[r_dialogue] 走吧，最后的难关。\n\
[l_dialogue] 嗯。\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/title.png\n\
[l_dialogue] 应该就在前面了！\n\
[convert_bg] image/black.png\n\
[center] 啊，来了吗？\n\
[convert_bg] image/title.png\n\
[l_dialogue] 可恶……最后的敌人了吗。\n\
[r_character] image/tsuki.png\n\
[r_dialogue] ……\n\
[l_dialogue] 月，你怎么了？\n\
[r_dialogue] 又是你吗……？\n\
[convert_bg] image/black.png\n\
[center] 我就知道，你一定会来。\n\
[center] 人类总是放不下自己的同伴接二连三往陷阱里跳呢……\n\
[center] 甚至不惜断送自己的性命吗。\n\
[center] 真是愚蠢之极。\n\
[convert_bg] image/title.png\n\
[r_character] image/tsuki.png\n\
[r_dialogue] 这可不一定。\n\
[r_dialogue] 今天会在这里断送性命的，不是我，而会是你！\n\
[convert_bg] image/black.png\n\
[center] 哼，有意思。\n\
[center] 区区人类也敢在我面前说出这种话。\n\
[center] 好了，时间不多了。\n\
[center] 那么……\n\
[play_bgm] music/bg6.mp3\n\
[center] 接下来，好好享受我给你们准备的盛宴吧！\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/bg.png\
"

var scenario_seven = "\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[center] 怎么可能……\n\
[convert_bg] image/title.png\n\
[l_dialogue] 解决了吗！\n\
[r_character] image/tsuki.png\n\
[r_dialogue] 不，还没有……\n\
[l_dialogue] 怎么可能……突然感觉到这么强的一股力量……\n\
[convert_bg] image/black.png\n\
[play_bgm] music/bg7.mp3\n\
[center] 竟然被一个人类逼到这种地步……姑且称赞你一下吧。\n\
[center] ……但是到此为止了。\n\
[center] 那就让你看看我真正的力量吧！\n\
[convert_bg] image/title.png\n\
[r_character] image/tsuki.png\n\
[r_dialogue] 放马过来吧！\n\
[r_dialogue] 我一定会在这里打倒你！\n\
[r_dialogue] 然后……\n\
[convert_bg] image/black.png\n\
[center] 一定会救出夜！！！\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/bg.png\
"

var scenario_eight = "\
[stop_bgm]\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[center] ……是你赢了。\n\
[center] 一个人类……竟然能有如此强的力量……\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[play_bgm] music/title.mp3\n\
[center] ……\n\
[center] 我……我这是怎么了？\n\
[center] 这是在哪里？\n\
[center] 周围一片黑暗，什么都看不到。\n\
[center] 脑海中一片混沌。\n\
[center] 能够勉强想起来的最后的事情，我和月两人被未知机体袭击。\n\
[center] 最后当敌人发动攻击时我一把推开了月……\n\
[center] 是吗……我已经死了吗？\n\
[center] 这里是死后的世界吗？\n\
[center] 好不甘心……\n\
[center] 我的人生就这么结束了吗……\n\
[center] ……\n\
[center] 不过……\n\
[center] 你能够活下去就好。\n\
[center] 你能活下去，我就很开心了。\n\
[center] ……虽然还是很不舍。\n\
[center] 好想再见你一面啊……\n\
[center] 哪怕再让我听到你的声音也行……\n\
[center] “……e”\n\
[center] 是幻觉吗，从什么地方传来了有些熟悉的声音。\n\
[center] “夜！”\n\
[center] 不，是熟悉得不能再熟悉的声音。\n\
[center] 我朝着声音传来的方向，然而还是什么都看不见。\n\
[center] “夜！快醒醒！”\n\
[center] 是吗，原来我还活着吗。\n\
[center] 原来，你还是来救我了吗。\n\
[center] “求你了！我不能失去你啊！”\n\
[center] 真是的，明明让你快点逃掉的。\n\
[center] 不过还是有那么一点高兴。\n\
[center] 我试着努力睁开眼睛。\n\
[center] 然后，一束光进入了我的世界。\n\
[center] 光中的那个模糊的身影，是那么的让人安心。\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[convert_bg] image/black.png\n\
[center] 就算这个世界即将走向毁灭。\n\
[center] 我们还拥有明天。\n\
[center] 只是这一点，就让我充满希望。\n\
[return]\
"

var scenario_list = [];
scenario_list.push(scenario_one, scenario_two, scenario_three, scenario_four, scenario_five, scenario_six, scenario_seven, scenario_eight);